#!/bin/bash
set -euo pipefail

# register-cron-jobs.sh — Install all host cron jobs, logrotate, and OpenClaw CLI crons
#
# Single entry point for ALL scheduled task registration:
#   1. Static host cron files (backup, session-prune)
#   2. Dynamic timezone-aware cron files (alerts, maintenance)
#   3. Logrotate config
#   4. OpenClaw CLI cron jobs (Daily VPS Health Check)
#
# Must run as root (writes to /etc/cron.d/ and /etc/logrotate.d/).
# Self-contained: sources config from source-config.sh (stack.env).

if [ "$(id -u)" -ne 0 ]; then
  echo "Error: must run as root (writes to /etc/cron.d/ and /etc/logrotate.d/)" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=source-config.sh
source "$SCRIPT_DIR/source-config.sh"

INSTALL_DIR="${STACK__STACK__INSTALL_DIR:?STACK__STACK__INSTALL_DIR not set in stack.env}"
CLAW_IDS="${STACK__CLAWS__IDS:?STACK__CLAWS__IDS not set in stack.env}"
CRON_EXPR="${STACK__HOST__HOSTALERT__CRON_EXPR:-30 9 * * *}"
CRON_TZ="${STACK__HOST__HOSTALERT__CRON_TZ:-}"
CHAT_ID="${ENV__HOSTALERT_TELEGRAM_CHAT_ID:-}"

# Emit CRON_TZ line only if timezone is set (empty = use VPS host timezone)
emit_cron_tz() {
  [ -n "$1" ] && echo "CRON_TZ=$1"
}

# Ensure shared log directory exists
mkdir -p "${INSTALL_DIR}/logs"
chown openclaw:openclaw "${INSTALL_DIR}/logs"

# ── Section 1: Install static host cron files ────────────────────────────────
# Pre-built by pre-deploy.mjs with {{INSTALL_DIR}} already resolved.

echo "=== Installing static cron files ==="

for cronfile in cron-openclaw-backup cron-openclaw-session-prune; do
  src="${INSTALL_DIR}/host/${cronfile}"
  dest="/etc/cron.d/${cronfile}"
  if [ -f "$src" ]; then
    cp "$src" "$dest"
    chmod 644 "$dest"
    echo "  Installed ${dest}"
  else
    echo "  Warning: ${src} not found, skipping" >&2
  fi
done

# ── Section 2: Generate timezone-aware cron files ─────────────────────────────
# Alert and maintenance schedules depend on timezone config — generated dynamically.

echo "=== Generating dynamic cron files ==="

# Alerter: 15-minute health checks (fixed schedule) + daily report (TZ-aware)
{
  echo "# Generated by register-cron-jobs.sh — DO NOT EDIT"
  echo "# Re-run: sudo bash ${INSTALL_DIR}/host/register-cron-jobs.sh"
  echo ""
  echo "# 15-minute health check (alerts on threshold breach)"
  echo "*/15 * * * * root ${INSTALL_DIR}/host/host-alert.sh"
  if [ -n "$CHAT_ID" ]; then
    echo ""
    echo "# Daily report — schedule: ${CRON_EXPR} (${CRON_TZ:-system tz})"
    emit_cron_tz "$CRON_TZ"
    echo "${CRON_EXPR} root ${INSTALL_DIR}/host/host-alert.sh --report"
  fi
} > /etc/cron.d/openclaw-alerts
chmod 644 /etc/cron.d/openclaw-alerts
echo "  Installed /etc/cron.d/openclaw-alerts"

# Maintenance: 30 minutes before daily report
# Parse hour and minute from CRON_EXPR (format: "M H * * *")
REPORT_MIN=$(echo "$CRON_EXPR" | awk '{print $1}')
REPORT_HOUR=$(echo "$CRON_EXPR" | awk '{print $2}')

# Subtract 30 minutes, handling hour wraparound
MAINT_MIN=$((REPORT_MIN - 30))
MAINT_HOUR=$REPORT_HOUR
if [ "$MAINT_MIN" -lt 0 ]; then
  MAINT_MIN=$((MAINT_MIN + 60))
  MAINT_HOUR=$(( (MAINT_HOUR - 1 + 24) % 24 ))
fi

{
  echo "# Generated by register-cron-jobs.sh — DO NOT EDIT"
  echo "# Runs 30 min before daily report (${CRON_EXPR} ${CRON_TZ:-system tz})"
  echo ""
  emit_cron_tz "$CRON_TZ"
  echo "${MAINT_MIN} ${MAINT_HOUR} * * * root ${INSTALL_DIR}/host/host-maintenance-check.sh"
} > /etc/cron.d/openclaw-maintenance
chmod 644 /etc/cron.d/openclaw-maintenance
echo "  Installed /etc/cron.d/openclaw-maintenance"

# ── Section 3: Install logrotate config ───────────────────────────────────────

echo "=== Installing logrotate config ==="

LOGROTATE_SRC="${INSTALL_DIR}/host/logrotate-openclaw"
if [ -f "$LOGROTATE_SRC" ]; then
  cp "$LOGROTATE_SRC" /etc/logrotate.d/openclaw
  chmod 644 /etc/logrotate.d/openclaw
  echo "  Installed /etc/logrotate.d/openclaw"
else
  echo "  Warning: ${LOGROTATE_SRC} not found, skipping" >&2
fi

# ── Section 5: Auto-update cron (host-side openclaw version updates) ──────────
# Schedule from stack.yml stack.openclaw.auto_update_time (default: 3:00 AM PST).
# Gated on STACK__STACK__OPENCLAW__AUTO_UPDATE — only installs if enabled.

echo "=== Installing auto-update cron ==="

AUTO_UPDATE_CRON_EXPR="${STACK__STACK__OPENCLAW__AUTO_UPDATE_CRON_EXPR:-0 3 * * *}"
AUTO_UPDATE_CRON_TZ="${STACK__STACK__OPENCLAW__AUTO_UPDATE_CRON_TZ:-${CRON_TZ}}"

if [ "${STACK__STACK__OPENCLAW__AUTO_UPDATE:-false}" = "true" ]; then
  {
    echo "# Generated by register-cron-jobs.sh — DO NOT EDIT"
    echo "# Daily openclaw version check and rebuild"
    echo ""
    emit_cron_tz "$AUTO_UPDATE_CRON_TZ"
    echo "${AUTO_UPDATE_CRON_EXPR} openclaw ${INSTALL_DIR}/host/auto-update-openclaw.sh >> ${INSTALL_DIR}/logs/auto-update.log 2>&1"
  } > /etc/cron.d/openclaw-auto-update
  chmod 644 /etc/cron.d/openclaw-auto-update
  echo "  Installed /etc/cron.d/openclaw-auto-update (${AUTO_UPDATE_CRON_EXPR} ${AUTO_UPDATE_CRON_TZ:-system tz})"
else
  # Remove stale cron if auto-update was disabled
  rm -f /etc/cron.d/openclaw-auto-update
  echo "  Auto-update disabled — skipped (removed stale cron if any)"
fi

# ── Section 4: Register OpenClaw CLI cron jobs ────────────────────────────────
# These use the openclaw CLI to register in-container scheduled tasks.
# Requires gateway container(s) to be running and healthy.

echo "=== Registering OpenClaw CLI cron jobs ==="

# Check that stack manifests exist (register-stack.sh should run before this)
if [ ! -d "/etc/openclaw-stacks" ] || [ -z "$(ls /etc/openclaw-stacks/*.env 2>/dev/null)" ]; then
  echo "  Warning: No stack manifests in /etc/openclaw-stacks/ — run register-stack.sh first."
  echo "  Host scripts (host-alert.sh, backup.sh, etc.) need manifests for cross-stack discovery."
fi

if ! command -v openclaw &>/dev/null; then
  echo "  openclaw CLI not available — containers may not be running yet."
  echo "  Re-run this script after containers are started to register CLI cron jobs."
  echo ""
  echo "Done. Host cron jobs and logrotate installed. CLI cron jobs skipped."
  exit 0
fi

# Build delivery flags (conditional on Telegram config)
DELIVERY_FLAGS=""
if [ -n "$CHAT_ID" ]; then
  DELIVERY_FLAGS="--channel telegram --to ${CHAT_ID}"
fi

# Register on each claw
IFS=',' read -ra CLAWS <<< "$CLAW_IDS"
for CLAW in "${CLAWS[@]}"; do
  echo "  Checking claw: $CLAW"

  # Check per-claw toggle (default: disabled)
  envKey=$(echo "$CLAW" | tr '-' '_' | tr '[:lower:]' '[:upper:]')
  varName="STACK__CLAWS__${envKey}__STATUS_REPORT_CRON"
  if [ "${!varName:-false}" != "true" ]; then
    echo "    Status report cron disabled for $CLAW, skipping."
    continue
  fi

  # Idempotent: skip if already registered
  # shellcheck disable=SC2086
  if openclaw --instance "$CLAW" cron list 2>/dev/null | grep -q "Daily VPS Status Report"; then
    echo "    Cron job 'Daily VPS Status Report' already registered on $CLAW, skipping."
    continue
  fi

  echo "    Registering 'Daily VPS Status Report' on $CLAW..."
  # shellcheck disable=SC2086
  openclaw --instance "$CLAW" cron add \
    --name "Daily VPS Status Report" \
    --cron "${CRON_EXPR}" \
    --tz "${CRON_TZ}" \
    --session isolated \
    --wake next-heartbeat \
    --agent main \
    --light-context \
    --announce \
    --best-effort-deliver \
    ${DELIVERY_FLAGS} \
    --message "Read the VPS status report files and analyze them:

1. Read /workspace/.host-status/health.json (resource metrics)
2. Read /workspace/.host-status/maintenance.json (OS maintenance)

Analyze for issues that need human attention:

Resource status (health.json):
- containers: inspect each entry — \"stopped\" or \"restarting\" means a claw is down
- containers_ok is false means at least one expected container is not running
- disk_pct approaching or exceeding disk_threshold
- memory_pct approaching or exceeding memory_threshold
- load_avg significantly above cpu_count
- docker_ok is false
- crashed is non-empty (unexpected containers restarting)
- backup_ok is false or backup_age_hours > 36
- timestamp older than 30 minutes (monitoring may be broken)

Maintenance status (maintenance.json):
- security_updates > 0 (pending security patches)
- reboot_required is true
- failed_services is not \"none\"
- uptime_days > 90 (consider scheduled reboot)
- timestamp older than 26 hours (maintenance monitor may not be running)

If everything looks good, respond with exactly: HEARTBEAT_OK

If any issues are found, send a concise alert with:
- What's wrong (use emoji indicators: critical, warning)
- Why it matters (one line per issue)
- Recommended action
Keep it brief - this goes to Telegram."

  echo "    Registered on $CLAW."
done

echo ""
echo "Done. All cron jobs, logrotate, and CLI cron registration complete for ${#CLAWS[@]} claw(s)."
